### ISSUE TITLE
Build and DOM errors

### ISSUE THREAD

**Issue by robdy** [robdy/robdy.io#551]
## Build

```
3:09:07 PM: warning Component Tip was not imported, exported, or provided by MDXProvider as global scope
3:09:07 PM: warning Component Tip was not imported, exported, or provided by MDXProvider as global scope
3:09:07 PM: warning Component Warning was not imported, exported, or provided by MDXProvider as global scope
3:09:07 PM: warning Component Warning was not imported, exported, or provided by MDXProvider as global scope
3:09:07 PM: warning Component Tip was not imported, exported, or provided by MDXProvider as global scope
3:09:07 PM: warning Component Tip was not imported, exported, or provided by MDXProvider as global scope
3:09:07 PM: warning Component Warning was not imported, exported, or provided by MDXProvider as global scope
3:09:07 PM: warning Component Note was not imported, exported, or provided by MDXProvider as global scope
```

https://github.com/gatsbyjs/gatsby/issues/20543

warn 
/workspaces/robdy.io/src/components/CodeBlock.js
  31:43  warning  'modifiedProps' is assigned a value but never used
                                                                                                               no-unused-vars
  36:5   warning  React Hook useEffect has a missing dependency: 'refresh'. Either include it or remove the dependency array.
You can also do a functional update 'setRefresh(r => ...)' if you only need 'refresh' in the 'setRefresh' call
react-hooks/exhaustive-deps

/workspaces/robdy.io/src/components/Comments.js
  13:11  warning  'theme' is assigned a value but never used  no-unused-vars

/workspaces/robdy.io/src/components/Navbar.js
  2:10  warning  'navigate' is defined but never used  no-unused-vars

/workspaces/robdy.io/src/templates/blog-post.js
  24:9  warning  'PostContent' is assigned a value but never used  no-unused-vars

✖ 5 problems (0 errors, 5 warnings)

## Client-side
```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `BlogRoll`. See https://reactjs.org/link/warning-keys for more information.
    at PostTile (webpack-internal:///./src/components/PostTile.js:25:29)
    at BlogRoll (webpack-internal:///./src/components/BlogRoll.js:26:73)
    at div
    at div
    at section
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at div
    at TemplateWrapper (webpack-internal:///./src/components/Layout.js:39:23)
    at BlogIndexPage (webpack-internal:///./src/pages/index.js:30:29)
    at PageRenderer (webpack-internal:///./.cache/page-renderer.js:30:29)
    at PageQueryStore (webpack-internal:///./.cache/query-result-store.js:46:30)
    at RouteHandler
    at div
    at FocusHandlerImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:359:5)
    at FocusHandler (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:330:19)
    at RouterImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:235:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Router
    at ScrollHandler (webpack-internal:///./node_modules/gatsby-react-router-scroll/scroll-handler.js:36:35)
    at RouteUpdates (webpack-internal:///./.cache/navigation.js:294:32)
    at EnsureResources (webpack-internal:///./.cache/ensure-resources.js:29:30)
    at LocationHandler (webpack-internal:///./.cache/root.js:67:29)
    at LocationProvider (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:84:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Root
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at MDXScopeProvider (webpack-internal:///./node_modules/gatsby-plugin-mdx/context.js:32:25)
    at _c (webpack-internal:///./node_modules/gatsby-plugin-mdx/wrap-root-element.js:128:37)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:122:48)
    at PartytownProvider (webpack-internal:///./node_modules/gatsby/dist/internal-plugins/partytown/gatsby-browser.js:17:3)
    at StaticQueryStore (webpack-internal:///./.cache/query-result-store.js:165:32)
    at ErrorBoundary (webpack-internal:///./.cache/fast-refresh-overlay/components/error-boundary.js:24:35)
    at DevOverlay (webpack-internal:///./.cache/fast-refresh-overlay/index.js:132:23)
    at RootWrappedWithOverlayAndProvider
    at App (webpack-internal:///./.cache/app.js:219:68)
printWarning @ react.development.js:220
react.development.js:220 
        
       Warning: Each child in a list should have a unique "key" prop.

Check the render method of `PostTile`. See https://reactjs.org/link/warning-keys for more information.
    at PostTile (webpack-internal:///./src/components/PostTile.js:25:29)
    at div
    at BlogRoll (webpack-internal:///./src/components/BlogRoll.js:26:73)
    at div
    at div
    at section
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at div
    at TemplateWrapper (webpack-internal:///./src/components/Layout.js:39:23)
    at BlogIndexPage (webpack-internal:///./src/pages/index.js:30:29)
    at PageRenderer (webpack-internal:///./.cache/page-renderer.js:30:29)
    at PageQueryStore (webpack-internal:///./.cache/query-result-store.js:46:30)
    at RouteHandler
    at div
    at FocusHandlerImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:359:5)
    at FocusHandler (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:330:19)
    at RouterImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:235:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Router
    at ScrollHandler (webpack-internal:///./node_modules/gatsby-react-router-scroll/scroll-handler.js:36:35)
    at RouteUpdates (webpack-internal:///./.cache/navigation.js:294:32)
    at EnsureResources (webpack-internal:///./.cache/ensure-resources.js:29:30)
    at LocationHandler (webpack-internal:///./.cache/root.js:67:29)
    at LocationProvider (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:84:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Root
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at MDXScopeProvider (webpack-internal:///./node_modules/gatsby-plugin-mdx/context.js:32:25)
    at _c (webpack-internal:///./node_modules/gatsby-plugin-mdx/wrap-root-element.js:128:37)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:122:48)
    at PartytownProvider (webpack-internal:///./node_modules/gatsby/dist/internal-plugins/partytown/gatsby-browser.js:17:3)
    at StaticQueryStore (webpack-internal:///./.cache/query-result-store.js:165:32)
    at ErrorBoundary (webpack-internal:///./.cache/fast-refresh-overlay/components/error-boundary.js:24:35)
    at DevOverlay (webpack-internal:///./.cache/fast-refresh-overlay/index.js:132:23)
    at RootWrappedWithOverlayAndProvider
    at App (webpack-internal:///./.cache/app.js:219:68)
printWarning @ react.development.js:220
react-dom.development.js:67 
        
       Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>.
    at a
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at eval (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:473:24)
    at GatsbyLink (webpack-internal:///./node_modules/gatsby-link/index.js:106:30)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at GatsbyLinkLocationWrapper
    at ul
    at div
    at article
    at div
    at a
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at eval (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:473:24)
    at GatsbyLink (webpack-internal:///./node_modules/gatsby-link/index.js:106:30)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at GatsbyLinkLocationWrapper
    at div
    at PostTile (webpack-internal:///./src/components/PostTile.js:25:29)
    at div
    at BlogRoll (webpack-internal:///./src/components/BlogRoll.js:26:73)
    at div
    at div
    at section
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at div
    at TemplateWrapper (webpack-internal:///./src/components/Layout.js:39:23)
    at BlogIndexPage (webpack-internal:///./src/pages/index.js:30:29)
    at PageRenderer (webpack-internal:///./.cache/page-renderer.js:30:29)
    at PageQueryStore (webpack-internal:///./.cache/query-result-store.js:46:30)
    at RouteHandler
    at div
    at FocusHandlerImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:359:5)
    at FocusHandler (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:330:19)
    at RouterImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:235:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Router
    at ScrollHandler (webpack-internal:///./node_modules/gatsby-react-router-scroll/scroll-handler.js:36:35)
    at RouteUpdates (webpack-internal:///./.cache/navigation.js:294:32)
    at EnsureResources (webpack-internal:///./.cache/ensure-resources.js:29:30)
    at LocationHandler (webpack-internal:///./.cache/root.js:67:29)
    at LocationProvider (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:84:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Root
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at MDXScopeProvider (webpack-internal:///./node_modules/gatsby-plugin-mdx/context.js:32:25)
    at _c (webpack-internal:///./node_modules/gatsby-plugin-mdx/wrap-root-element.js:128:37)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:122:48)
    at PartytownProvider (webpack-internal:///./node_modules/gatsby/dist/internal-plugins/partytown/gatsby-browser.js:17:3)
    at StaticQueryStore (webpack-internal:///./.cache/query-result-store.js:165:32)
    at ErrorBoundary (webpack-internal:///./.cache/fast-refresh-overlay/components/error-boundary.js:24:35)
    at DevOverlay (webpack-internal:///./.cache/fast-refresh-overlay/index.js:132:23)
    at RootWrappedWithOverlayAndProvider
    at App (webpack-internal:///./.cache/app.js:219:68)
printWarning @ react-dom.development.js:67
:8000/favicon.ico:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
plausible.js:1 
        
       Ignoring Event: localhost
l @ plausible.js:1
:8000/favicon.ico:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: the server responded with a status of 404 (Not Found)
:33889/socket.io/?EIO=4&transport=polling&t=O4-HE3G:1 
        
      
        
        
      
        
      
       
        
       Failed to load resource: net::ERR_CONNECTION_REFUSED
plausible.js:1 
        
       Ignoring Event: localhost
l @ plausible.js:1
react.development.js:220 
        
       Warning: Each child in a list should have a unique "key" prop.

Check the render method of `BlogPostTemplate`. See https://reactjs.org/link/warning-keys for more information.
    at BlogPostTemplate (webpack-internal:///./src/templates/blog-post.js:39:22)
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at div
    at TemplateWrapper (webpack-internal:///./src/components/Layout.js:39:23)
    at BlogPost (webpack-internal:///./src/templates/blog-post.js:205:20)
    at PageRenderer (webpack-internal:///./.cache/page-renderer.js:30:29)
    at PageQueryStore (webpack-internal:///./.cache/query-result-store.js:46:30)
    at RouteHandler
    at div
    at FocusHandlerImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:359:5)
    at FocusHandler (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:330:19)
    at RouterImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:235:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Router
    at ScrollHandler (webpack-internal:///./node_modules/gatsby-react-router-scroll/scroll-handler.js:36:35)
    at RouteUpdates (webpack-internal:///./.cache/navigation.js:294:32)
    at EnsureResources (webpack-internal:///./.cache/ensure-resources.js:29:30)
    at LocationHandler (webpack-internal:///./.cache/root.js:67:29)
    at LocationProvider (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:84:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Root
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at MDXScopeProvider (webpack-internal:///./node_modules/gatsby-plugin-mdx/context.js:32:25)
    at _c (webpack-internal:///./node_modules/gatsby-plugin-mdx/wrap-root-element.js:128:37)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:122:48)
    at PartytownProvider (webpack-internal:///./node_modules/gatsby/dist/internal-plugins/partytown/gatsby-browser.js:17:3)
    at StaticQueryStore (webpack-internal:///./.cache/query-result-store.js:165:32)
    at ErrorBoundary (webpack-internal:///./.cache/fast-refresh-overlay/components/error-boundary.js:24:35)
    at DevOverlay (webpack-internal:///./.cache/fast-refresh-overlay/index.js:132:23)
    at RootWrappedWithOverlayAndProvider
    at App (webpack-internal:///./.cache/app.js:219:68)
printWarning @ react.development.js:220
react-dom.development.js:67 
        
       Warning: Invalid DOM property `datetime`. Did you mean `dateTime`?
    at time
    at p
    at div
    at div
    at section
    at BlogPostTemplate (webpack-internal:///./src/templates/blog-post.js:39:22)
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at div
    at TemplateWrapper (webpack-internal:///./src/components/Layout.js:39:23)
    at BlogPost (webpack-internal:///./src/templates/blog-post.js:205:20)
    at PageRenderer (webpack-internal:///./.cache/page-renderer.js:30:29)
    at PageQueryStore (webpack-internal:///./.cache/query-result-store.js:46:30)
    at RouteHandler
    at div
    at FocusHandlerImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:359:5)
    at FocusHandler (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:330:19)
    at RouterImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:235:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Router
    at ScrollHandler (webpack-internal:///./node_modules/gatsby-react-router-scroll/scroll-handler.js:36:35)
    at RouteUpdates (webpack-internal:///./.cache/navigation.js:294:32)
    at EnsureResources (webpack-internal:///./.cache/ensure-resources.js:29:30)
    at LocationHandler (webpack-internal:///./.cache/root.js:67:29)
    at LocationProvider (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:84:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Root
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at MDXScopeProvider (webpack-internal:///./node_modules/gatsby-plugin-mdx/context.js:32:25)
    at _c (webpack-internal:///./node_modules/gatsby-plugin-mdx/wrap-root-element.js:128:37)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:122:48)
    at PartytownProvider (webpack-internal:///./node_modules/gatsby/dist/internal-plugins/partytown/gatsby-browser.js:17:3)
    at StaticQueryStore (webpack-internal:///./.cache/query-result-store.js:165:32)
    at ErrorBoundary (webpack-internal:///./.cache/fast-refresh-overlay/components/error-boundary.js:24:35)
    at DevOverlay (webpack-internal:///./.cache/fast-refresh-overlay/index.js:132:23)
    at RootWrappedWithOverlayAndProvider
    at App (webpack-internal:///./.cache/app.js:219:68)
printWarning @ react-dom.development.js:67
react-dom.development.js:67 
        
       Warning: React does not recognize the `parentName` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `parentname` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at code
    at pre
    at CodeBlock (webpack-internal:///./src/components/CodeBlock.js:18:67)
    at pre (webpack-internal:///./src/components/Layout.js:412:30)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at div
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at wrapper (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:149:25)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at MDXContent (eval at _construct (webpack-internal:///./node_modules/@babel/runtime/helpers/construct.js), <anonymous>:27:25)
    at MDXRenderer (webpack-internal:///./node_modules/gatsby-plugin-mdx/mdx-renderer.js:59:20)
    at div
    at section
    at BlogPostTemplate (webpack-internal:///./src/templates/blog-post.js:39:22)
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at div
    at TemplateWrapper (webpack-internal:///./src/components/Layout.js:39:23)
    at BlogPost (webpack-internal:///./src/templates/blog-post.js:205:20)
    at PageRenderer (webpack-internal:///./.cache/page-renderer.js:30:29)
    at PageQueryStore (webpack-internal:///./.cache/query-result-store.js:46:30)
    at RouteHandler
    at div
    at FocusHandlerImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:359:5)
    at FocusHandler (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:330:19)
    at RouterImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:235:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Router
    at ScrollHandler (webpack-internal:///./node_modules/gatsby-react-router-scroll/scroll-handler.js:36:35)
    at RouteUpdates (webpack-internal:///./.cache/navigation.js:294:32)
    at EnsureResources (webpack-internal:///./.cache/ensure-resources.js:29:30)
    at LocationHandler (webpack-internal:///./.cache/root.js:67:29)
    at LocationProvider (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:84:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Root
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at MDXScopeProvider (webpack-internal:///./node_modules/gatsby-plugin-mdx/context.js:32:25)
    at _c (webpack-internal:///./node_modules/gatsby-plugin-mdx/wrap-root-element.js:128:37)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:122:48)
    at PartytownProvider (webpack-internal:///./node_modules/gatsby/dist/internal-plugins/partytown/gatsby-browser.js:17:3)
    at StaticQueryStore (webpack-internal:///./.cache/query-result-store.js:165:32)
    at ErrorBoundary (webpack-internal:///./.cache/fast-refresh-overlay/components/error-boundary.js:24:35)
    at DevOverlay (webpack-internal:///./.cache/fast-refresh-overlay/index.js:132:23)
    at RootWrappedWithOverlayAndProvider
    at App (webpack-internal:///./.cache/app.js:219:68)
printWarning @ react-dom.development.js:67
react-dom.development.js:67 
        
       Warning: React does not recognize the `originalType` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `originaltype` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at code
    at pre
    at CodeBlock (webpack-internal:///./src/components/CodeBlock.js:18:67)
    at pre (webpack-internal:///./src/components/Layout.js:412:30)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at div
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at wrapper (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:149:25)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at MDXContent (eval at _construct (webpack-internal:///./node_modules/@babel/runtime/helpers/construct.js), <anonymous>:27:25)
    at MDXRenderer (webpack-internal:///./node_modules/gatsby-plugin-mdx/mdx-renderer.js:59:20)
    at div
    at section
    at BlogPostTemplate (webpack-internal:///./src/templates/blog-post.js:39:22)
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at div
    at TemplateWrapper (webpack-internal:///./src/components/Layout.js:39:23)
    at BlogPost (webpack-internal:///./src/templates/blog-post.js:205:20)
    at PageRenderer (webpack-internal:///./.cache/page-renderer.js:30:29)
    at PageQueryStore (webpack-internal:///./.cache/query-result-store.js:46:30)
    at RouteHandler
    at div
    at FocusHandlerImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:359:5)
    at FocusHandler (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:330:19)
    at RouterImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:235:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Router
    at ScrollHandler (webpack-internal:///./node_modules/gatsby-react-router-scroll/scroll-handler.js:36:35)
    at RouteUpdates (webpack-internal:///./.cache/navigation.js:294:32)
    at EnsureResources (webpack-internal:///./.cache/ensure-resources.js:29:30)
    at LocationHandler (webpack-internal:///./.cache/root.js:67:29)
    at LocationProvider (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:84:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Root
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at MDXScopeProvider (webpack-internal:///./node_modules/gatsby-plugin-mdx/context.js:32:25)
    at _c (webpack-internal:///./node_modules/gatsby-plugin-mdx/wrap-root-element.js:128:37)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:122:48)
    at PartytownProvider (webpack-internal:///./node_modules/gatsby/dist/internal-plugins/partytown/gatsby-browser.js:17:3)
    at StaticQueryStore (webpack-internal:///./.cache/query-result-store.js:165:32)
    at ErrorBoundary (webpack-internal:///./.cache/fast-refresh-overlay/components/error-boundary.js:24:35)
    at DevOverlay (webpack-internal:///./.cache/fast-refresh-overlay/index.js:132:23)
    at RootWrappedWithOverlayAndProvider
    at App (webpack-internal:///./.cache/app.js:219:68)
printWarning @ react-dom.development.js:67
react-dom.development.js:67 
        
       Warning: React does not recognize the `mdxType` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `mdxtype` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    at code
    at pre
    at CodeBlock (webpack-internal:///./src/components/CodeBlock.js:18:67)
    at pre (webpack-internal:///./src/components/Layout.js:412:30)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at div
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at wrapper (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:149:25)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:154:30)
    at MDXContent (eval at _construct (webpack-internal:///./node_modules/@babel/runtime/helpers/construct.js), <anonymous>:27:25)
    at MDXRenderer (webpack-internal:///./node_modules/gatsby-plugin-mdx/mdx-renderer.js:59:20)
    at div
    at section
    at BlogPostTemplate (webpack-internal:///./src/templates/blog-post.js:39:22)
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at div
    at TemplateWrapper (webpack-internal:///./src/components/Layout.js:39:23)
    at BlogPost (webpack-internal:///./src/templates/blog-post.js:205:20)
    at PageRenderer (webpack-internal:///./.cache/page-renderer.js:30:29)
    at PageQueryStore (webpack-internal:///./.cache/query-result-store.js:46:30)
    at RouteHandler
    at div
    at FocusHandlerImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:359:5)
    at FocusHandler (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:330:19)
    at RouterImpl (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:235:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Router
    at ScrollHandler (webpack-internal:///./node_modules/gatsby-react-router-scroll/scroll-handler.js:36:35)
    at RouteUpdates (webpack-internal:///./.cache/navigation.js:294:32)
    at EnsureResources (webpack-internal:///./.cache/ensure-resources.js:29:30)
    at LocationHandler (webpack-internal:///./.cache/root.js:67:29)
    at LocationProvider (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:84:5)
    at Location (webpack-internal:///./node_modules/@gatsbyjs/reach-router/es/index.js:64:23)
    at Root
    at MDXProvider (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:139:46)
    at MDXScopeProvider (webpack-internal:///./node_modules/gatsby-plugin-mdx/context.js:32:25)
    at _c (webpack-internal:///./node_modules/gatsby-plugin-mdx/wrap-root-element.js:128:37)
    at eval (webpack-internal:///./node_modules/@mdx-js/react/dist/esm.js:122:48)
    at PartytownProvider (webpack-internal:///./node_modules/gatsby/dist/internal-plugins/partytown/gatsby-browser.js:17:3)
    at StaticQueryStore (webpack-internal:///./.cache/query-result-store.js:165:32)
    at ErrorBoundary (webpack-internal:///./.cache/fast-refresh-overlay/components/error-boundary.js:24:35)
    at DevOverlay (webpack-internal:///./.cache/fast-refresh-overlay/index.js:132:23)
    at RootWrappedWithOverlayAndProvider
    at App (webpack-internal:///./.cache/app.js:219:68)
```

## Client-side (`/`)

```
Warning: validateDOMNesting(...): <a> cannot appear as a descendant of <a>. - for tag links in the article pane
```

**Comment by robdy** [comment]
Partially resolved in #552
